"api":
  - changed-files:
      - any-glob-to-any-file: "apps/api/**"
"ui":
  - changed-files:
      - any-glob-to-any-file: "apps/ui/**"
"worker":
  - changed-files:
      - any-glob-to-any-file: "apps/worker/**"
"checks":
  - changed-files:
      - any-glob-to-any-file: "packages/checks/**"
"db":
  - changed-files:
      - any-glob-to-any-file: "apps/api/alembic/versions/**"
"ci":
  - changed-files:
      - any-glob-to-any-file: [".github/**"]
