"API":
  - changed-files:
      - any-glob-to-any-file: "apps/api/**"
"UX/UI":
  - changed-files:
      - any-glob-to-any-file: "apps/ui/**"
"worker":
  - changed-files:
      - any-glob-to-any-file: "apps/worker/**"
"checks":
  - changed-files:
      - any-glob-to-any-file: "packages/checks/**"
"db":
  - changed-files:
      - any-glob-to-any-file: "apps/api/alembic/versions/**"
"CI/CD":
  - changed-files:
      - any-glob-to-any-file: [".github/**"]
